version: '3.3'
services:
  postgres:
    image: postgres:12.8
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "scalaql"
    volumes:
      - ./integration-tests/db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
