addSbtPlugin("com.eed3si9n"        % "sbt-projectmatrix" % "0.8.0")
addSbtPlugin("org.scalameta"       % "sbt-scalafmt"      % "2.4.6")
addSbtPlugin("org.jetbrains.scala" % "sbt-ide-settings"  % "1.1.1")
addSbtPlugin("com.github.sbt"      % "sbt-ci-release"    % "1.5.10")
addSbtPlugin("com.github.sbt"      % "sbt-jacoco"        % "3.4.0")
