addSbtPlugin("com.eed3si9n"        % "sbt-projectmatrix" % "0.8.0")
addSbtPlugin("org.scalameta"       % "sbt-scalafmt"      % "2.4.6")
addSbtPlugin("org.jetbrains.scala" % "sbt-ide-settings"  % "1.1.1")
addSbtPlugin("org.xerial.sbt"      % "sbt-sonatype"      % "3.9.13")
addSbtPlugin("com.jsuereth"        % "sbt-pgp"           % "2.0.1")
