name: Site publish
on:
  push:
    tags: [ "*" ]
  workflow_dispatch:    
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Scala
        uses: olafurpg/setup-scala@v13
      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier
          key: sbt-cache-${{ runner.os }}-${{ matrix.target-platform }}-${{ hashFiles('project/build.properties') }}
      - name: Compile
        run: sbt +compile
      - name: Generate doc
        run: sbt docs/mdoc
      - name: Generate site
        working-directory: 'website'
        run: yarn install && yarn run build
      - name: Install wrangler
        run: npm i -g wrangler
      - name: Publish
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: npx wrangler pages publish --project-name=scala-ql --commit-dirty=true build/
